services:
  bootstraphoverdropdown:
    image: bootstraphoverdropdown
    build:
      context: crm/rukovoditel_3.6.2/template/plugins/bootstrap-hover-dropdown
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
